//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp11
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentsView
    {
        public string ФИО_пациента { get; set; }
        public string ФИО_врача { get; set; }
        public System.DateTime Дата_приема { get; set; }
        public string Описание { get; set; }
    }
}
