//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp11
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentsView2
    {
        public string PatientFullName { get; set; }
        public string DoctorFullName { get; set; }
        public System.DateTime DateAppointment { get; set; }
        public string DescriptionAppointment { get; set; }
        public int ID_Patient { get; set; }
        public int ID_Doctor { get; set; }
    }
}
