//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp11
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClinicView
    {
        public string Фамилия_пациента { get; set; }
        public string Имя_пациента { get; set; }
        public string Отчество_пациента { get; set; }
        public string Пол_пациента { get; set; }
        public System.DateTime Дата_рождения_пациента { get; set; }
        public string Фамилия_врача { get; set; }
        public string Имя_врача { get; set; }
        public string Отчество_врача { get; set; }
        public string Специализация { get; set; }
        public System.DateTime Дата_приема { get; set; }
        public string Описание_приема { get; set; }
    }
}
