//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp11
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorsView2
    {
        public string DoctorSurname { get; set; }
        public string DoctorName { get; set; }
        public string DoctorMiddleName { get; set; }
        public string SpecializationName { get; set; }
    }
}
