//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp11
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientsView2
    {
        public int ID_Patient { get; set; }
        public string PatientSurname { get; set; }
        public string PatientName { get; set; }
        public string PatientMiddleName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int Gender_ID { get; set; }
        public string GenderValue { get; set; }
    }
}
